# GAME CONFIGURATION
TICK_DELAY = 0.1
MAX_TICKS = 2

# TEAM SETTINGS
PLAYERS_RED = ["Alice", "Bob", "Eve"]
PLAYERS_BLUE = ["Charlie", "Diana", "Frank"]

# MAP SETTINGS
SOURCE_FOLDER: str = "assets/maps/"

# UI SETTINGS
TILE_SIZE = 30
MESSAGE_BOX_HEIGHT = 120
MESSAGE_BOX_MARGIN = 10
MAX_MESSAGES = 6
