# GAME CONFIGURATION
TICK_DELAY = 0.5
MAX_TICKS = 200

# TEAM SETTINGS
PLAYERS_RED = ["Alice", "Bob", "Eve"]
PLAYERS_BLUE = ["Charlie", "Diana", "Frank"]

# MAP SETTINGS
SOURCE_FOLDER: str = "assets/maps/"

# UI SETTINGS
TILE_SIZE = 30
MESSAGE_BOX_HEIGHT = 120
MESSAGE_BOX_MARGIN = 10
MAX_MESSAGES = 6
PLAYER_TAG_SIZE = 10
